initial QUIC BBR text
mwelzl/draft-iccrg-pacing pull request #8
Opened 2024-07-02 00:56 UTC by wesley-eddy

Initial content for QUIC BBR section, and other small suggested edits.

2024-07-02 11:00 UTC, mwelzl requested changes
A few minor suggestions - but this is a great PR, thanks!  I learned some pretty interesting things here, I wasn't aware of the token-based schemes (they make sense of course, but I just hadn't seen them before)

2024-07-03 13:51 UTC, wesley-eddy commented on draft-welzl-iccrg-pacing.md
> +Pacing capability is expected in QUIC senders.  While standard QUIC congestion control {{RFC9002}} is based on TCP NewReno, which does not include pacing, QUIC congestion control requires either paci
Yes this is good.  Just an odd thing to note: 9002 actually says "NewReno", but I agree with you (and Yuchung).

2024-07-03 13:58 UTC, wesley-eddy commented
Thanks for the edits Michael!  I think I've responded to your other comments too.

2024-07-03 14:20 UTC, mwelzl approved these changes

2024-07-03 14:22 UTC, merged